### ISSUE TITLE
Getting "Undefined property: Laravel\\Scout\\Builder::$offset"

### ISSUE THREAD

**Issue by hmazter** [damiantw/laravel-scout-mysql-driver#1]
Getting `"Undefined property: Laravel\\Scout\\Builder::$offset"`
on line 73 in `damiantw/laravel-scout-mysql-driver/src/Engines/MySQLEngine.php` which reads: 
`if($this->builder->offset) {`

This happens when i do: `Child::search($q)->get();`

Using PHP 7.0.8 in homestead

**Comment by damiantw** [comment]
Thanks!
