### ISSUE TITLE
Model detection does not detect namespaces

### ISSUE THREAD

**Issue by jbrooksuk** [damiantw/laravel-scout-mysql-driver#11]
If, like me, you move your models into a `Models` namespace, the package fails to detect the namespace change.

**Comment by ionut-tanasa** [comment]
I just installed the package and I have the same situation. A `Models` folder inside app. It throws an exception like @jbrooksuk said

**Comment by msonowal** [comment]
same here

**Comment by msonowal** [comment]
@jbrooksuk @ionut-tanasa its fixed in v1.0.10 #
