### ISSUE TITLE
Not compatible with Scout 2

### ISSUE THREAD

**Issue by azcoppen** [damiantw/laravel-scout-mysql-driver#12]
Using version ^1.0 for damiantw/laravel-scout-mysql-driver                                                                      
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                        
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - damiantw/laravel-scout-mysql-driver v1.0.4 requires laravel/scout ^1.1 -> satisfiable by laravel/scout[v1.1.10, v1.1.11, v1.1.12, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7, v1.1.8, v1.1.9] but these conflict with your requirements or minimum-stability.
    - damiantw/laravel-scout-mysql-driver v1.0.3 requires laravel/scout ^1.1 -> satisfiable by laravel/scout[v1.1.10, v1.1.11, v1.1.12, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7, v1.1.8, v1.1.9] but these conflict with your requirements or minimum-stability.
    - damiantw/laravel-scout-mysql-driver v1.0.2 requires laravel/scout ^1.1 -> satisfiable by laravel/scout[v1.1.10, v1.1.11, v1.1.12, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7, v1.1.8, v1.1.9] but these conflict with your requirements or minimum-stability.
    - damiantw/laravel-scout-mysql-driver v1.0.1 requires laravel/scout ^1.1 -> satisfiable by laravel/scout[v1.1.10, v1.1.11, v1.1.12, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7, v1.1.8, v1.1.9] but these conflict with your requirements or minimum-stability.
    - damiantw/laravel-scout-mysql-driver v1.0.0 requires laravel/scout ^1.1 -> satisfiable by laravel/scout[v1.1.10, v1.1.11, v1.1.12, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7, v1.1.8, v1.1.9] but these conflict with your requirements or minimum-stability.
    - Installation request for damiantw/laravel-scout-mysql-driver ^1.0 -> satisfiable by damiantw/laravel-scout-mysql-driver[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4].

Installation failed, reverting ./composer.json to its original content.

**Comment by jonathan-bird** [comment]
+1 would love this

**Comment by sullyfischer** [comment]
+1

**Comment by thomaswardiii** [comment]
There was a commit a few hours ago that adds Laravel Scout 3 and Laravel 5.4 references. Try it now?

**Comment by sullyfischer** [comment]
I forked it myself, and it's working fine. Is there anything else added? (other than updating the composer.json file)

**Comment by thomaswardiii** [comment]
@sullyfischer No but you should look at how it was implemented here since the method used here is backwards compatible with 5.3 and 5.4 Laravel and multiple versions of Scout
