### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by rawzone** [damiantw/laravel-scout-mysql-driver#18]
Would love to see Laravel 5.4 support.

Currently this happens when running 
`composer require damiantw/laravel-scout-mysql-driver`

You gets
`damiantw/laravel-scout-mysql-driver v1.0.6 requires laravel/framework 5.3.*`

**Comment by hmazter** [comment]
I have a branch with that here: https://github.com/hmazter/laravel-scout-mysql-driver/tree/allow-laravel-54
But I haven't been able to test it yet in a 5.4 project that uses Scout.

**Comment by rawzone** [comment]
@hmazter Awesome! Ill give that a try - I'm just starting work on a prototype app in 5.4. Will let you know if anything strange comes up.

Thanks
