### ISSUE TITLE
Not compatible with Scout 3

### ISSUE THREAD

**Issue by mixisLv** [damiantw/laravel-scout-mysql-driver#20]
composer.json

>         "laravel/scout": "^3.0",
>         "damiantw/laravel-scout-mysql-driver": "^1.0"

Problem:
damiantw/laravel-scout-mysql-driver v1.0.7 requires laravel/scout ^2.0

**Comment by Shpartko** [comment]
+1

**Comment by poyhsiao** [comment]
can send "pull request" ?

**Comment by thomaswardiii** [comment]
There was a commit a few hours ago that adds Laravel Scout 3 and Laravel 5.4 references. Try it now?

**Comment by mixisLv** [comment]
it  works!
