### ISSUE TITLE
Not compatible with Laravel 5.4

### ISSUE THREAD

**Issue by xDestinatioNx** [damiantw/laravel-scout-mysql-driver#21]
composer.json

    "laravel/framework": "5.4.*",
    "laravel/scout": "^3.0",
    "damiantw/laravel-scout-mysql-driver": "^1.0"

Problem:
`damiantw/laravel-scout-mysql-driver v1.0.7` requires `laravel/framework 5.3.*` and `laravel/scout ^2.0`

**Comment by thomaswardiii** [comment]
There was a commit a few hours ago that adds Laravel Scout 3 and Laravel 5.4 references. Try it now?
