### ISSUE TITLE
Getting Trait 'Illuminate\Console\DetectsApplicationNamespace' not found error

### ISSUE THREAD

**Issue by pwnz22** [damiantw/laravel-scout-mysql-driver#24]
Getting Trait 'Illuminate\Console\DetectsApplicationNamespace' not found error when install and set the provider. After that i cant do the command php artisan vendor:publish. But if i comment the laravel-scout-mysql-driver provider the error is gone. 

Laravel version is 5.3.18

**Comment by pwnz22** [comment]
For Laravel 5.3 need to change `use Illuminate\Console\DetectsApplicationNamespace;` to use `Illuminate\Console\AppNamespaceDetectorTrait;`

**Comment by DMeganoski** [comment]
Curious, why did you close this? It is still an issue. It is, in most cases, a bad idea to modify composer libraries, as changes can be overwritten with an update. And unless this is addressed, that is exactly what will happen. 

I understand the developer does not have much time. I may be able to create a couple pull requests with new versions for 5.3 and 5.4.
