### ISSUE TITLE
Syntax error or access violation: 1070 Too many key parts specified; max 16 parts allowed

### ISSUE THREAD

**Issue by azcoppen** [damiantw/laravel-scout-mysql-driver#27]
I have a lot of text fields - is it possible to specify which fields to index? Doing the import as is results in a nasty error.

**Comment by ChrisThompsonTLDR** [comment]
Yes, use the Laravel Scout documentation: https://laravel.com/docs/5.3/scout#configuring-searchable-data

Posting the error would help us help you debug the issue.
