### ISSUE TITLE
QueryException in Connection.php line 761: Can't find FULLTEXT index matching 

### ISSUE THREAD

**Issue by rob1121** [damiantw/laravel-scout-mysql-driver#3]
QueryException in Connection.php line 761:
SQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list (SQL: select count(*) as aggregate from `company_specs` where MATCH(spec_no,name) AGAINST(:_search IN NATURAL LANGUAGE MODE))

**Comment by hmazter** [comment]
@rob1121 Quick question, have you executed the command to generate the index? 
`php artisan scout:mysql-index App\\Post` (for your Model/Models)

**Comment by rob1121** [comment]
sorry... not reading documentation well.. My bad.. Thanks Sir
